In [1]:
import numpy as np

In [3]:
temp = np.array([1,2,3])
print(type(temp))

<class 'numpy.ndarray'>


In [4]:
# numpy : A와 B 배열을 더하면, A배열과 B배열의 값이 각각 덧셈 형태로 변환된다.

In [5]:
data1 = [1,2,3]
data1

[1, 2, 3]

In [6]:
data2 = [1,1,2,2,3,4]
data2

[1, 1, 2, 2, 3, 4]

In [7]:
# 만들어진 리스트를 np.aaray를 통해 배열로 변환.
my_array1 = np.array(data1)
print(my_array1)
print(my_array1.shape)

[1 2 3]
(3,)


In [8]:
my_array2 = np.array(data2)
print(my_array2)
print(my_array2.shape)

[1 1 2 2 3 4]
(6,)


In [9]:
# 꼭 1개를 넣는 것이 아닌 여러 개를 동시에 넣을 수도 있다.
my_array4 = np.array([[2,3,1],[1,2,3],[4,5,6],[7,8,9]])
my_array4

array([[2, 3, 1],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
my_array4.shape

(4, 3)

In [11]:
# 4행 3열인 데이터라는 것을 알 수 있음.

In [13]:
my_array5 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
my_array5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
my_array5.shape

(2, 2, 2)

In [15]:
# 3차원의 배열 데이터로 2*2*2의 크기를 가집니다.

In [16]:
# 기본함수들

In [17]:
arrange_array = np.arange(5)
arrange_array

array([0, 1, 2, 3, 4])

In [18]:
# 1부터 9미만까지 3단위
np.arange(1,9,3)

array([1, 4, 7])

In [19]:
#zeros, ones

In [20]:
zeros_array = np.zeros((3,5),dtype='int32')
print(zeros_array)
print("Data Type is :", zeros_array.dtype)
print("Data Shape is :", zeros_array.shape)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Data Type is : int32
Data Shape is : (3, 5)


In [22]:
# Reshape : 특정 차원에서 열은 고정한 상태로 행은 사이즈에 맞도록 자동으로 정렬
# np.reshape(-1,x)

In [23]:
temp_arr = np.array([1,2,3,4,5,6,7,8,9,10])
temp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
new_arr = temp_arr.reshape(2,-1)
new_arr
# 2행으로 고정한 상태에서 열을 사이즈 맞도록 자동 정렬

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
new_arr2 = temp_arr.shape(4,-1)
new_arr2
# 개수에 맞지 않으면 error 도출

TypeError: 'tuple' object is not callable

In [28]:
# 정렬 : np.sort()
# 내림차순 정렬 : [[:`-1]]
# 지정된 축에 따라 데이터 인덱스의 배열을 반환하도록 지정된 종류의 정렬을 사용해 입력 배열에서 간접 정렬을 수행 : argsort()

In [32]:
fives = np.array([10,5,15,20])
fives_order = fives.argsort()

print('The original data : ',fives)
print('The argsort():',fives_order)
print('The ascending:',fives[fives_order])
print('오름차순 정렬 : ',np.sort(fives))
print('내림차순 정렬 : ',np.sort(fives)[::-1])

The original data :  [10  5 15 20]
The argsort(): [1 0 2 3]
The ascending: [ 5 10 15 20]
오름차순 정렬 :  [ 5 10 15 20]
내림차순 정렬 :  [20 15 10  5]
